export function generateHTMLReport({ flowName, ranAt, duration, results, workspaceName = "Denis's Command Center" }) {
  const dateStr = new Date(ranAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const timeStr = new Date(ranAt).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });
  const durationStr = duration > 60000 ? `${Math.round(duration/60000)}m` : `${Math.round(duration/1000)}s`;

  const agentSections = results.map(r => `
    <div class="agent-section">
      <div class="agent-header">
        <div class="agent-icon" style="background: ${r.agentColor || '#F0C040'}22; border-color: ${r.agentColor || '#F0C040'}44; color: ${r.agentColor || '#F0C040'}">
          ${r.agentIcon || '◎'}
        </div>
        <div>
          <div class="agent-name">${r.agentName}</div>
          <div class="agent-task">${r.task || ''}</div>
        </div>
      </div>
      <div class="agent-output">${formatOutput(r.output || '')}</div>
    </div>
  `).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${flowName} — ${dateStr}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Syne:wght@600;700;800&family=DM+Sans:wght@400;500&family=DM+Mono:wght@400;500&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'DM Sans', sans-serif; background: #07070f; color: #fff; padding: 40px; max-width: 860px; margin: 0 auto; }
    .header { border-bottom: 1px solid #ffffff15; padding-bottom: 28px; margin-bottom: 32px; }
    .logo { color: #F0C040; font-family: 'Syne', sans-serif; font-weight: 800; font-size: 13px; letter-spacing: 3px; margin-bottom: 12px; }
    h1 { font-family: 'Syne', sans-serif; font-weight: 800; font-size: 32px; color: #fff; margin-bottom: 8px; }
    .meta { display: flex; gap: 20px; flex-wrap: wrap; }
    .meta-item { display: flex; align-items: center; gap: 6px; color: #ffffff66; font-family: 'DM Mono', monospace; font-size: 12px; }
    .meta-value { color: #ffffffcc; }
    .badge { background: #F0C04022; border: 1px solid #F0C04044; color: #F0C040; padding: 3px 10px; border-radius: 20px; font-family: 'DM Mono', monospace; font-size: 11px; }
    .agent-section { background: rgba(255,255,255,0.04); border: 1px solid #ffffff0f; border-radius: 14px; padding: 22px; margin-bottom: 20px; }
    .agent-header { display: flex; align-items: flex-start; gap: 14px; margin-bottom: 16px; }
    .agent-icon { width: 40px; height: 40px; border-radius: 10px; border: 1.5px solid; display: flex; align-items: center; justify-content: center; font-size: 18px; flex-shrink: 0; }
    .agent-name { font-family: 'Syne', sans-serif; font-weight: 700; font-size: 16px; color: #fff; }
    .agent-task { color: #ffffff66; font-size: 12px; font-family: 'DM Mono', monospace; margin-top: 3px; }
    .agent-output { color: #ffffffcc; font-size: 14px; line-height: 1.7; white-space: pre-wrap; }
    .agent-output li { margin-left: 16px; margin-bottom: 6px; }
    footer { margin-top: 48px; text-align: center; color: #ffffff22; font-family: 'DM Mono', monospace; font-size: 11px; border-top: 1px solid #ffffff0a; padding-top: 24px; }
    @media print { body { background: #fff; color: #000; } .agent-section { border-color: #ccc; background: #f9f9f9; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">◈ AGENTIC OS — ${workspaceName.toUpperCase()}</div>
    <h1>${flowName}</h1>
    <div class="meta">
      <div class="meta-item">📅 <span class="meta-value">${dateStr} at ${timeStr}</span></div>
      <div class="meta-item">⏱ <span class="meta-value">${durationStr}</span></div>
      <div class="meta-item">◎ <span class="meta-value">${results.length} agents</span></div>
      <div class="badge">COMPLETED</div>
    </div>
  </div>
  ${agentSections}
  <footer>Generated by AgenticOS · deniskyla-auto.vercel.app</footer>
</body>
</html>`;
}

function formatOutput(text) {
  return text
    .split('\n')
    .map(line => {
      const trimmed = line.trim();
      if (trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*') || /^\d+\./.test(trimmed)) {
        return `<li>${trimmed.replace(/^[•\-\*\d\.]+\s*/, '')}</li>`;
      }
      return `<p>${trimmed}</p>`;
    })
    .join('\n');
}
