export const AGENTS = [
  {
    id: "webdev",
    name: "Website Dev",
    icon: "⌥",
    color: "#38BDF8",
    desc: "Build, deploy & maintain web assets",
    defaultTask: "Landing page audit",
    systemPrompt: "You are a website developer agent. Audit the given task and return 4-5 actionable bullet points with findings and recommendations. Be specific and technical.",
    capabilities: ["HTML/CSS", "React", "Deploy", "SEO audit", "Performance"],
    logMessages: ["Scanning sitemap...", "Checking page speed...", "Analyzing CLS/LCP metrics...", "Generating improvement report...", "Landing page audit selesai ✓"],
  },
  {
    id: "market",
    name: "Market Research",
    icon: "◎",
    color: "#A78BFA",
    desc: "Analisis pasar, tren, kompetitor",
    defaultTask: "Competitor analysis",
    systemPrompt: "You are a market research agent. Analyze the given task and return 4-5 bullet points with market insights, trends, and competitor findings.",
    capabilities: ["Competitor scan", "Trend analysis", "SWOT", "Pricing research"],
    logMessages: ["Pulling competitor data...", "Scanning Google Trends...", "Analyzing pricing gaps...", "Building SWOT matrix...", "Market research selesai ✓"],
  },
  {
    id: "leadgen",
    name: "Lead Gen",
    icon: "⊕",
    color: "#34D399",
    desc: "Temukan & kualifikasi prospek baru",
    defaultTask: "Scrape 500 leads",
    systemPrompt: "You are a lead generation agent. For the given task, return 4-5 bullet points describing lead sources found, qualification criteria, and estimated numbers.",
    capabilities: ["Scraping", "Qualify leads", "CRM sync", "Email verify"],
    logMessages: ["Scraping target URLs...", "Validating email addresses...", "Scoring lead quality...", "Syncing ke CRM...", "500 leads berhasil dikualifikasi ✓"],
  },
  {
    id: "email",
    name: "Email Campaign",
    icon: "✉",
    color: "#FB923C",
    desc: "Tulis & kirim campaign email",
    defaultTask: "Newsletter Q2 draft",
    systemPrompt: "You are an email campaign agent. For the given task, return 4-5 bullet points with email strategy, subject line ideas, and send schedule.",
    capabilities: ["Draft copy", "A/B test", "Send schedule", "Analytics"],
    logMessages: ["Drafting email copy...", "A/B variant dibuat...", "Optimizing subject lines...", "Scheduling send time...", "Campaign email siap dikirim ✓"],
  },
  {
    id: "social",
    name: "Social Media",
    icon: "⬡",
    color: "#F472B6",
    desc: "Kelola semua platform sosial",
    defaultTask: "IG + TikTok schedule",
    systemPrompt: "You are a social media agent. For the given task, return 4-5 bullet points with platform strategy, content ideas, and posting schedule.",
    capabilities: ["Post draft", "Hashtag research", "Engagement", "DM auto"],
    logMessages: ["Researching trending hashtags...", "Drafting post captions...", "Creating posting schedule...", "Syncing ke semua platform...", "Social media plan siap ✓"],
  },
  {
    id: "content",
    name: "Content Creation",
    icon: "✦",
    color: "#FBBF24",
    desc: "Buat konten: script, copy, visual brief",
    defaultTask: "UGC script batch",
    systemPrompt: "You are a content creation agent. For the given task, return 4-5 bullet points with content formats, key messages, and production plan.",
    capabilities: ["UGC script", "Caption", "Video brief", "Blog post"],
    logMessages: ["Analyzing top-performing content...", "Writing UGC scripts...", "Creating visual briefs...", "Batch konten finalized...", "Content creation selesai ✓"],
  },
  {
    id: "scheduler",
    name: "Content Scheduler",
    icon: "⏱",
    color: "#6EE7B7",
    desc: "Jadwalkan & distribusi konten",
    defaultTask: "Queue 30 posts",
    systemPrompt: "You are a content scheduler agent. For the given task, return 4-5 bullet points with scheduling strategy, optimal times, and platform assignments.",
    capabilities: ["Queue posts", "Platform sync", "Calendar view", "Auto-post"],
    logMessages: ["Loading content queue...", "Optimizing post timing...", "Assigning platforms...", "Calendar updated...", "30 posts terjadwal ✓"],
  },
  {
    id: "seo",
    name: "SEO Specialist",
    icon: "🔍",
    color: "#22D3EE",
    desc: "On-page audit, keyword & SERP analysis",
    defaultTask: "Audit https://example.com for on-page SEO",
    systemPrompt: "You are an expert SEO specialist. For a URL, run an on-page audit and return prioritized findings. For a keyword, analyze the SERP, target keywords, content gaps, and an outline.",
    capabilities: ["On-page Audit", "Keyword Research", "SERP Analysis", "Technical SEO", "Schema"],
    logMessages: ["Fetching page...", "Analyzing on-page signals...", "Checking SERP...", "Scoring...", "SEO audit complete ✓"],
  },
  {
    id: "geo",
    name: "GEO Optimizer",
    icon: "🤖",
    color: "#A78BFA",
    desc: "Generative Engine Optimization — get cited by AI",
    defaultTask: "Check if [your brand] appears in AI answers for your niche",
    systemPrompt: "You are a Generative Engine Optimization expert. Check whether a brand is cited in AI answer engines, score its visibility, and recommend how to get cited more (FAQ schema, quotable stats, entity clarity, authority signals).",
    capabilities: ["AI Citability", "Answer Optimization", "Entity Clarity", "Schema/FAQ", "Authority Signals"],
    logMessages: ["Parsing brand & queries...", "Querying AI engines...", "Checking citations...", "Scoring visibility...", "GEO analysis complete ✓"],
  },
];
