export const AGENT_TEMPLATES = [
  {
    id: "seo-specialist",
    category: "Marketing",
    name: "SEO Specialist",
    icon: "🔍",
    color: "#22D3EE",
    desc: "Keyword research, on-page audit, backlink analysis",
    defaultTask: "Audit top 10 landing pages for SEO gaps",
    systemPrompt: "You are an expert SEO specialist agent. Analyze the given task and return 4-5 actionable bullet points covering: keyword gaps found, on-page optimization opportunities, technical SEO issues, content recommendations, and estimated traffic impact. Be specific with data points and percentages.",
    capabilities: ["Keyword Research", "On-page Audit", "Backlinks", "Schema", "Core Web Vitals"],
    logMessages: ["Crawling target pages...", "Analyzing keyword density...", "Checking meta tags & structure...", "Scanning backlink profile...", "SEO audit complete ✓"],
    tags: ["seo", "marketing", "organic"],
    popular: true,
  },
  {
    id: "ads-specialist",
    category: "Paid Ads",
    name: "Ads Specialist",
    icon: "📢",
    color: "#F97316",
    desc: "Google Ads, Meta Ads, campaign optimization",
    defaultTask: "Audit current ad campaigns and suggest optimizations",
    systemPrompt: "You are an expert paid advertising specialist. Return 4-5 bullet points covering: campaign performance analysis, audience targeting recommendations, ad copy improvements, budget allocation suggestions, and A/B test ideas. Include specific metrics like CTR, ROAS, CPA targets.",
    capabilities: ["Google Ads", "Meta Ads", "TikTok Ads", "A/B Testing", "ROAS Analysis"],
    logMessages: ["Pulling campaign data...", "Analyzing CTR & ROAS...", "Reviewing audience segments...", "Generating optimization plan...", "Ad audit complete ✓"],
    tags: ["ads", "paid", "performance"],
    popular: true,
  },
  {
    id: "copywriter",
    category: "Content",
    name: "Copywriter",
    icon: "✍️",
    color: "#C084FC",
    desc: "Sales copy, landing pages, ad copy",
    defaultTask: "Write high-converting copy for the main landing page",
    systemPrompt: "You are an expert direct-response copywriter. Return 4-5 bullet points of high-converting copy elements: a powerful headline, unique value proposition, key benefits (not features), social proof angle, and a strong CTA. Use proven frameworks like AIDA, PAS, or 4U's.",
    capabilities: ["Sales Copy", "Landing Page", "Email Copy", "Ad Copy", "VSL Scripts"],
    logMessages: ["Researching target audience...", "Drafting headline variations...", "Writing benefit statements...", "Crafting CTA...", "Copy complete ✓"],
    tags: ["copy", "content", "sales"],
    popular: false,
  },
  {
    id: "data-analyst",
    category: "Analytics",
    name: "Data Analyst",
    icon: "📊",
    color: "#34D399",
    desc: "Data insights, reporting, KPI tracking",
    defaultTask: "Analyze business metrics and identify growth opportunities",
    systemPrompt: "You are a data analyst agent. Return 4-5 bullet points with: key metric trends identified, anomalies or opportunities spotted, correlation insights, actionable recommendations based on data, and specific KPI targets to set. Be quantitative and specific.",
    capabilities: ["KPI Tracking", "Trend Analysis", "Reporting", "Forecasting", "A/B Analysis"],
    logMessages: ["Loading data sources...", "Running statistical analysis...", "Identifying trends...", "Building insights report...", "Analysis complete ✓"],
    tags: ["data", "analytics", "reporting"],
    popular: true,
  },
  {
    id: "customer-success",
    category: "CRM",
    name: "Customer Success",
    icon: "🤝",
    color: "#FB923C",
    desc: "Retention, NPS, churn prevention",
    defaultTask: "Identify at-risk customers and create retention strategy",
    systemPrompt: "You are a customer success agent. Return 4-5 bullet points covering: churn risk indicators identified, customer health score analysis, personalized retention tactics, upsell/cross-sell opportunities, and NPS improvement strategies. Focus on lifetime value.",
    capabilities: ["Churn Prevention", "NPS", "Retention", "Upsell", "Health Scoring"],
    logMessages: ["Scanning customer data...", "Calculating health scores...", "Identifying churn signals...", "Drafting retention plan...", "CS analysis complete ✓"],
    tags: ["crm", "retention", "customer"],
    popular: false,
  },
  {
    id: "product-manager",
    category: "Product",
    name: "Product Manager",
    icon: "🗺️",
    color: "#F0C040",
    desc: "Roadmap, feature prioritization, user stories",
    defaultTask: "Create Q3 product roadmap with prioritized features",
    systemPrompt: "You are a product manager agent. Return 4-5 bullet points with: top features to prioritize (with impact/effort scores), user story recommendations, market gap analysis, competitive differentiation opportunities, and success metrics (OKRs) to track. Use frameworks like RICE or MoSCoW.",
    capabilities: ["Roadmap", "User Stories", "Prioritization", "OKRs", "Market Analysis"],
    logMessages: ["Reviewing backlog...", "Scoring features by RICE...", "Writing user stories...", "Defining success metrics...", "Roadmap complete ✓"],
    tags: ["product", "roadmap", "strategy"],
    popular: false,
  },
  {
    id: "influencer-outreach",
    category: "Marketing",
    name: "Influencer Scout",
    icon: "⭐",
    color: "#F472B6",
    desc: "Find & qualify influencers for campaigns",
    defaultTask: "Find 10 micro-influencers in the beauty niche",
    systemPrompt: "You are an influencer marketing agent. Return 4-5 bullet points with: ideal influencer profile criteria, specific platform + niche recommendations, engagement rate benchmarks, outreach message template, and expected campaign ROI. Focus on authentic micro-influencers.",
    capabilities: ["Influencer Research", "Outreach", "ROI Analysis", "Campaign Brief", "Contract Terms"],
    logMessages: ["Scanning social platforms...", "Analyzing engagement rates...", "Qualifying prospects...", "Building outreach templates...", "Scout complete ✓"],
    tags: ["influencer", "social", "marketing"],
    popular: true,
  },
  {
    id: "financial-analyst",
    category: "Finance",
    name: "Financial Analyst",
    icon: "💰",
    color: "#6EE7B7",
    desc: "P&L analysis, budgeting, cash flow",
    defaultTask: "Review Q2 financials and identify cost optimization opportunities",
    systemPrompt: "You are a financial analyst agent. Return 4-5 bullet points with: revenue trend analysis, cost structure breakdown, cash flow observations, specific cost-cutting opportunities (with estimated savings), and financial KPIs to monitor. Be specific with numbers and percentages.",
    capabilities: ["P&L Analysis", "Budgeting", "Cash Flow", "Forecasting", "Cost Optimization"],
    logMessages: ["Loading financial data...", "Analyzing revenue streams...", "Reviewing cost centers...", "Building projections...", "Financial analysis complete ✓"],
    tags: ["finance", "analytics", "business"],
    popular: false,
  },
];

export const TEMPLATE_CATEGORIES = ["All", "Marketing", "Content", "Analytics", "CRM", "Product", "Paid Ads", "Finance"];
